
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet_health?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 1000  # 客户端连接超时时间
      # 连接池配置
      lettuce:
        pool:
          max-active: 200  # 连接池最大活跃连接数
          max-wait: -1     # 连接池最大阻塞等待时间
          max-idle: 10     # 连接池最大空闲连接数
          min-idle: 0      # 连接池最小空闲连接数

  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**

  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: notify-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  servlet:
    context-path: /api

snowflake:
  worker-id: 0
  datacenter-id: 0

mybatis-plus:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.jacob.common.model
  configuration:
      log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 分页
pagehelper:
  helper-dialect: mysql
  page-size-zero: true
  reasonable: true
  auto-runtime-dialect: true

# JWT配置
jwt:
  secret: "d83Kf93kD8f9K3jf9skd83jf9sdf93jf9sdf83jf9K3jf9sdf"
  expire-time: 7200000

# 日志配置
logging:
  level:
    com.jacob.dao.mappers: DEBUG
    org.apache.ibatis: DEBUG
    org.springframework.jdbc: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: web/logs/mybatis-sql.log
    max-size: 10MB
    max-history: 7