
appender=com.p6spy.engine.spy.appender.StdoutLogger

logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat

customLogMessageFormat=执行SQL：%(sql) | 耗时：%(executionTime) ms | 连接信息：%(connectionId)

excludeCommmands=SET NAMES,SET CHARACTER SET

useParameterMetadata=false

includeComments=false

append=true